// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/Microsoft/hcsshim/cmd/ncproxy/nodenetsvc/nodenetsvc.proto

package nodenetsvc

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	reflect "reflect"
	strings "strings"

	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RequestType int32

const (
	RequestType_RequestType_Setup    RequestType = 0
	RequestType_RequestType_Teardown RequestType = 1
)

var RequestType_name = map[int32]string{
	0: "RequestType_Setup",
	1: "RequestType_Teardown",
}

var RequestType_value = map[string]int32{
	"RequestType_Setup":    0,
	"RequestType_Teardown": 1,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}

func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{0}
}

type ConfigureNetworkingRequest struct {
	ContainerID          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigureNetworkingRequest) Reset()      { *m = ConfigureNetworkingRequest{} }
func (*ConfigureNetworkingRequest) ProtoMessage() {}
func (*ConfigureNetworkingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{0}
}
func (m *ConfigureNetworkingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigureNetworkingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigureNetworkingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigureNetworkingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureNetworkingRequest.Merge(m, src)
}
func (m *ConfigureNetworkingRequest) XXX_Size() int {
	return m.Size()
}
func (m *ConfigureNetworkingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureNetworkingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureNetworkingRequest proto.InternalMessageInfo

type ConfigureNetworkingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigureNetworkingResponse) Reset()      { *m = ConfigureNetworkingResponse{} }
func (*ConfigureNetworkingResponse) ProtoMessage() {}
func (*ConfigureNetworkingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{1}
}
func (m *ConfigureNetworkingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigureNetworkingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigureNetworkingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigureNetworkingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureNetworkingResponse.Merge(m, src)
}
func (m *ConfigureNetworkingResponse) XXX_Size() int {
	return m.Size()
}
func (m *ConfigureNetworkingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureNetworkingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureNetworkingResponse proto.InternalMessageInfo

type PingNodeNetworkServiceRequest struct {
	PingRequestMessage   string   `protobuf:"bytes,1,opt,name=pingRequestMessage,proto3" json:"pingRequestMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingNodeNetworkServiceRequest) Reset()      { *m = PingNodeNetworkServiceRequest{} }
func (*PingNodeNetworkServiceRequest) ProtoMessage() {}
func (*PingNodeNetworkServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{2}
}
func (m *PingNodeNetworkServiceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PingNodeNetworkServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PingNodeNetworkServiceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PingNodeNetworkServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingNodeNetworkServiceRequest.Merge(m, src)
}
func (m *PingNodeNetworkServiceRequest) XXX_Size() int {
	return m.Size()
}
func (m *PingNodeNetworkServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingNodeNetworkServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingNodeNetworkServiceRequest proto.InternalMessageInfo

type PingNodeNetworkServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingNodeNetworkServiceResponse) Reset()      { *m = PingNodeNetworkServiceResponse{} }
func (*PingNodeNetworkServiceResponse) ProtoMessage() {}
func (*PingNodeNetworkServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{3}
}
func (m *PingNodeNetworkServiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PingNodeNetworkServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PingNodeNetworkServiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PingNodeNetworkServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingNodeNetworkServiceResponse.Merge(m, src)
}
func (m *PingNodeNetworkServiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *PingNodeNetworkServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingNodeNetworkServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingNodeNetworkServiceResponse proto.InternalMessageInfo

type ConfigureContainerNetworkingRequest struct {
	RequestType          RequestType `protobuf:"varint,1,opt,name=request_type,json=requestType,proto3,enum=azure.nodenetworkservice.RequestType" json:"request_type,omitempty"`
	ContainerID          string      `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	NetworkNamespace     string      `protobuf:"bytes,3,opt,name=network_namespace,json=networkNamespace,proto3" json:"network_namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConfigureContainerNetworkingRequest) Reset()      { *m = ConfigureContainerNetworkingRequest{} }
func (*ConfigureContainerNetworkingRequest) ProtoMessage() {}
func (*ConfigureContainerNetworkingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{4}
}
func (m *ConfigureContainerNetworkingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigureContainerNetworkingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigureContainerNetworkingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigureContainerNetworkingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureContainerNetworkingRequest.Merge(m, src)
}
func (m *ConfigureContainerNetworkingRequest) XXX_Size() int {
	return m.Size()
}
func (m *ConfigureContainerNetworkingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureContainerNetworkingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureContainerNetworkingRequest proto.InternalMessageInfo

type ConfigureContainerNetworkingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResponseJson         string   `protobuf:"bytes,2,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	ErrorJson            string   `protobuf:"bytes,3,opt,name=error_json,json=errorJson,proto3" json:"error_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigureContainerNetworkingResponse) Reset()      { *m = ConfigureContainerNetworkingResponse{} }
func (*ConfigureContainerNetworkingResponse) ProtoMessage() {}
func (*ConfigureContainerNetworkingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{5}
}
func (m *ConfigureContainerNetworkingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigureContainerNetworkingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigureContainerNetworkingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigureContainerNetworkingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureContainerNetworkingResponse.Merge(m, src)
}
func (m *ConfigureContainerNetworkingResponse) XXX_Size() int {
	return m.Size()
}
func (m *ConfigureContainerNetworkingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureContainerNetworkingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureContainerNetworkingResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("azure.nodenetworkservice.RequestType", RequestType_name, RequestType_value)
	proto.RegisterType((*ConfigureNetworkingRequest)(nil), "azure.nodenetworkservice.ConfigureNetworkingRequest")
	proto.RegisterType((*ConfigureNetworkingResponse)(nil), "azure.nodenetworkservice.ConfigureNetworkingResponse")
	proto.RegisterType((*PingNodeNetworkServiceRequest)(nil), "azure.nodenetworkservice.PingNodeNetworkServiceRequest")
	proto.RegisterType((*PingNodeNetworkServiceResponse)(nil), "azure.nodenetworkservice.PingNodeNetworkServiceResponse")
	proto.RegisterType((*ConfigureContainerNetworkingRequest)(nil), "azure.nodenetworkservice.ConfigureContainerNetworkingRequest")
	proto.RegisterType((*ConfigureContainerNetworkingResponse)(nil), "azure.nodenetworkservice.ConfigureContainerNetworkingResponse")
}

func init() {
	proto.RegisterFile("github.com/Microsoft/hcsshim/cmd/ncproxy/nodenetsvc/nodenetsvc.proto", fileDescriptor_3a65404bd96160d4)
}

var fileDescriptor_3a65404bd96160d4 = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xce, 0x52, 0x09, 0xe8, 0x24, 0x40, 0xba, 0xfc, 0xc8, 0x0a, 0xc4, 0x54, 0x6e, 0x91, 0x10,
	0x48, 0xb6, 0x14, 0x40, 0x70, 0xa1, 0x87, 0xb6, 0x07, 0x8a, 0xd4, 0x50, 0xb9, 0x3d, 0x71, 0xb1,
	0xdc, 0xf5, 0xd4, 0x59, 0x50, 0x76, 0xcd, 0xae, 0xdd, 0x12, 0x4e, 0x08, 0x71, 0xe3, 0x19, 0x78,
	0x1e, 0x7a, 0xec, 0x91, 0x13, 0xa2, 0x7e, 0x12, 0x44, 0xd6, 0x4e, 0x22, 0x25, 0x0e, 0xa4, 0xb7,
	0x9d, 0x6f, 0xfe, 0xbe, 0xf9, 0x76, 0x76, 0x61, 0x3b, 0xe6, 0x69, 0x2f, 0x3b, 0x74, 0x99, 0xec,
	0x7b, 0xbb, 0x9c, 0x29, 0xa9, 0xe5, 0x51, 0xea, 0xf5, 0x98, 0xd6, 0x3d, 0xde, 0xf7, 0x58, 0x3f,
	0xf2, 0x04, 0x4b, 0x94, 0xfc, 0x38, 0xf0, 0x84, 0x8c, 0x50, 0x60, 0xaa, 0x8f, 0xd9, 0xc4, 0xd1,
	0x4d, 0x94, 0x4c, 0x25, 0xb5, 0xc2, 0x4f, 0x99, 0x42, 0xb7, 0xc0, 0x4f, 0xa4, 0x7a, 0xaf, 0x51,
	0x1d, 0x73, 0x86, 0xce, 0x1e, 0xb4, 0xb6, 0xa4, 0x38, 0xe2, 0x71, 0xa6, 0xb0, 0x6b, 0x5c, 0x5c,
	0xc4, 0x3e, 0x7e, 0xc8, 0x50, 0xa7, 0xb4, 0x03, 0x0d, 0x26, 0x45, 0x1a, 0x72, 0x81, 0x2a, 0xe0,
	0x91, 0x45, 0x56, 0xc9, 0xc3, 0xe5, 0xcd, 0x1b, 0xf9, 0xaf, 0xfb, 0xf5, 0xad, 0x12, 0xdf, 0xd9,
	0xf6, 0xeb, 0xa3, 0xa0, 0x9d, 0xc8, 0x69, 0xc3, 0xdd, 0x99, 0x15, 0x75, 0x22, 0x85, 0x46, 0xe7,
	0x0d, 0xb4, 0xf7, 0xb8, 0x88, 0xbb, 0x32, 0x2a, 0xbd, 0xfb, 0x86, 0x4a, 0xd9, 0xd3, 0x05, 0x9a,
	0x8c, 0x29, 0xec, 0xa2, 0xd6, 0x61, 0x8c, 0xa6, 0xb3, 0x3f, 0xc3, 0xe3, 0xac, 0x82, 0x5d, 0x55,
	0xb0, 0x68, 0x79, 0x46, 0x60, 0x6d, 0x44, 0x69, 0xc4, 0x7b, 0x7a, 0xda, 0x57, 0xd0, 0x50, 0xe6,
	0x18, 0xa4, 0x83, 0xc4, 0xf4, 0xbc, 0xde, 0x79, 0xe0, 0x56, 0x89, 0xe7, 0x16, 0x89, 0x07, 0x83,
	0x04, 0xfd, 0xba, 0x1a, 0x1b, 0x53, 0xba, 0x5d, 0xfa, 0xb7, 0x6e, 0xf4, 0x31, 0xac, 0x14, 0xe5,
	0x03, 0x11, 0xf6, 0x51, 0x27, 0x21, 0x43, 0x6b, 0x69, 0x38, 0x76, 0xb3, 0x70, 0x74, 0x4b, 0xdc,
	0xf9, 0x4a, 0x60, 0x7d, 0xfe, 0x48, 0x66, 0x76, 0x6a, 0xc1, 0x15, 0x9d, 0x31, 0x86, 0x5a, 0x0f,
	0xc7, 0xb9, 0xea, 0x97, 0x26, 0x5d, 0x83, 0x6b, 0xaa, 0x88, 0x0a, 0xde, 0x69, 0x29, 0x0c, 0x49,
	0xbf, 0x51, 0x82, 0xaf, 0xb5, 0x14, 0xb4, 0x0d, 0x80, 0x4a, 0x49, 0x65, 0x22, 0x0c, 0x9b, 0xe5,
	0x21, 0xf2, 0xd7, 0xfd, 0x68, 0x03, 0xea, 0x13, 0x1a, 0xd0, 0xdb, 0xb0, 0x32, 0x61, 0x06, 0xfb,
	0x98, 0x66, 0x49, 0xb3, 0x46, 0x2d, 0xb8, 0x35, 0x09, 0x1f, 0x60, 0xa8, 0x22, 0x79, 0x22, 0x9a,
	0xa4, 0xf3, 0x63, 0x09, 0xe8, 0xf4, 0xc5, 0xd1, 0x2f, 0x04, 0x6e, 0xce, 0xd8, 0x21, 0xfa, 0xb4,
	0xfa, 0x2a, 0xaa, 0x97, 0xb8, 0xf5, 0x6c, 0xc1, 0xac, 0x42, 0xb9, 0xef, 0x04, 0xee, 0xcd, 0x93,
	0x98, 0xbe, 0xfc, 0x8f, 0xba, 0xd5, 0xdb, 0xd6, 0xda, 0xb8, 0x68, 0x7a, 0xc1, 0xef, 0x1b, 0x81,
	0x3b, 0xb3, 0x17, 0x9f, 0x3e, 0xaf, 0x2e, 0x3d, 0xf7, 0xed, 0xb5, 0x5e, 0x2c, 0x9e, 0x68, 0xd8,
	0x6c, 0xae, 0x9f, 0x9e, 0xdb, 0xb5, 0x9f, 0xe7, 0x76, 0xed, 0x73, 0x6e, 0x93, 0xd3, 0xdc, 0x26,
	0x67, 0xb9, 0x4d, 0x7e, 0xe7, 0x36, 0x79, 0x0b, 0xe3, 0xdf, 0xe8, 0xf0, 0xf2, 0xf0, 0x3b, 0x7a,
	0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x80, 0xc6, 0x36, 0xb7, 0xd6, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeNetworkServiceClient is the client API for NodeNetworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeNetworkServiceClient interface {
	ConfigureNetworking(ctx context.Context, in *ConfigureNetworkingRequest, opts ...grpc.CallOption) (*ConfigureNetworkingResponse, error)
	ConfigureContainerNetworking(ctx context.Context, in *ConfigureContainerNetworkingRequest, opts ...grpc.CallOption) (*ConfigureContainerNetworkingResponse, error)
	PingNodeNetworkService(ctx context.Context, in *PingNodeNetworkServiceRequest, opts ...grpc.CallOption) (*PingNodeNetworkServiceResponse, error)
}

type nodeNetworkServiceClient struct {
	cc *grpc.ClientConn
}

func NewNodeNetworkServiceClient(cc *grpc.ClientConn) NodeNetworkServiceClient {
	return &nodeNetworkServiceClient{cc}
}

func (c *nodeNetworkServiceClient) ConfigureNetworking(ctx context.Context, in *ConfigureNetworkingRequest, opts ...grpc.CallOption) (*ConfigureNetworkingResponse, error) {
	out := new(ConfigureNetworkingResponse)
	err := c.cc.Invoke(ctx, "/azure.nodenetworkservice.NodeNetworkService/ConfigureNetworking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeNetworkServiceClient) ConfigureContainerNetworking(ctx context.Context, in *ConfigureContainerNetworkingRequest, opts ...grpc.CallOption) (*ConfigureContainerNetworkingResponse, error) {
	out := new(ConfigureContainerNetworkingResponse)
	err := c.cc.Invoke(ctx, "/azure.nodenetworkservice.NodeNetworkService/ConfigureContainerNetworking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeNetworkServiceClient) PingNodeNetworkService(ctx context.Context, in *PingNodeNetworkServiceRequest, opts ...grpc.CallOption) (*PingNodeNetworkServiceResponse, error) {
	out := new(PingNodeNetworkServiceResponse)
	err := c.cc.Invoke(ctx, "/azure.nodenetworkservice.NodeNetworkService/PingNodeNetworkService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeNetworkServiceServer is the server API for NodeNetworkService service.
type NodeNetworkServiceServer interface {
	ConfigureNetworking(context.Context, *ConfigureNetworkingRequest) (*ConfigureNetworkingResponse, error)
	ConfigureContainerNetworking(context.Context, *ConfigureContainerNetworkingRequest) (*ConfigureContainerNetworkingResponse, error)
	PingNodeNetworkService(context.Context, *PingNodeNetworkServiceRequest) (*PingNodeNetworkServiceResponse, error)
}

func RegisterNodeNetworkServiceServer(s *grpc.Server, srv NodeNetworkServiceServer) {
	s.RegisterService(&_NodeNetworkService_serviceDesc, srv)
}

func _NodeNetworkService_ConfigureNetworking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureNetworkingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeNetworkServiceServer).ConfigureNetworking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/azure.nodenetworkservice.NodeNetworkService/ConfigureNetworking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeNetworkServiceServer).ConfigureNetworking(ctx, req.(*ConfigureNetworkingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeNetworkService_ConfigureContainerNetworking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureContainerNetworkingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeNetworkServiceServer).ConfigureContainerNetworking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/azure.nodenetworkservice.NodeNetworkService/ConfigureContainerNetworking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeNetworkServiceServer).ConfigureContainerNetworking(ctx, req.(*ConfigureContainerNetworkingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeNetworkService_PingNodeNetworkService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingNodeNetworkServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeNetworkServiceServer).PingNodeNetworkService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/azure.nodenetworkservice.NodeNetworkService/PingNodeNetworkService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeNetworkServiceServer).PingNodeNetworkService(ctx, req.(*PingNodeNetworkServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeNetworkService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "azure.nodenetworkservice.NodeNetworkService",
	HandlerType: (*NodeNetworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigureNetworking",
			Handler:    _NodeNetworkService_ConfigureNetworking_Handler,
		},
		{
			MethodName: "ConfigureContainerNetworking",
			Handler:    _NodeNetworkService_ConfigureContainerNetworking_Handler,
		},
		{
			MethodName: "PingNodeNetworkService",
			Handler:    _NodeNetworkService_PingNodeNetworkService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/Microsoft/hcsshim/cmd/ncproxy/nodenetsvc/nodenetsvc.proto",
}

func (m *ConfigureNetworkingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigureNetworkingRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ContainerID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.ContainerID)))
		i += copy(dAtA[i:], m.ContainerID)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ConfigureNetworkingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigureNetworkingResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *PingNodeNetworkServiceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingNodeNetworkServiceRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.PingRequestMessage) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.PingRequestMessage)))
		i += copy(dAtA[i:], m.PingRequestMessage)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *PingNodeNetworkServiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingNodeNetworkServiceResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ConfigureContainerNetworkingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigureContainerNetworkingRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RequestType != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(m.RequestType))
	}
	if len(m.ContainerID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.ContainerID)))
		i += copy(dAtA[i:], m.ContainerID)
	}
	if len(m.NetworkNamespace) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.NetworkNamespace)))
		i += copy(dAtA[i:], m.NetworkNamespace)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ConfigureContainerNetworkingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigureContainerNetworkingResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Success {
		dAtA[i] = 0x8
		i++
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.ResponseJson) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.ResponseJson)))
		i += copy(dAtA[i:], m.ResponseJson)
	}
	if len(m.ErrorJson) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.ErrorJson)))
		i += copy(dAtA[i:], m.ErrorJson)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintNodenetsvc(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ConfigureNetworkingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContainerID)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ConfigureNetworkingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PingNodeNetworkServiceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PingRequestMessage)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PingNodeNetworkServiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ConfigureContainerNetworkingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestType != 0 {
		n += 1 + sovNodenetsvc(uint64(m.RequestType))
	}
	l = len(m.ContainerID)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	l = len(m.NetworkNamespace)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ConfigureContainerNetworkingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	l = len(m.ResponseJson)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	l = len(m.ErrorJson)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovNodenetsvc(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozNodenetsvc(x uint64) (n int) {
	return sovNodenetsvc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ConfigureNetworkingRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ConfigureNetworkingRequest{`,
		`ContainerID:` + fmt.Sprintf("%v", this.ContainerID) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ConfigureNetworkingResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ConfigureNetworkingResponse{`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PingNodeNetworkServiceRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PingNodeNetworkServiceRequest{`,
		`PingRequestMessage:` + fmt.Sprintf("%v", this.PingRequestMessage) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PingNodeNetworkServiceResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PingNodeNetworkServiceResponse{`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ConfigureContainerNetworkingRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ConfigureContainerNetworkingRequest{`,
		`RequestType:` + fmt.Sprintf("%v", this.RequestType) + `,`,
		`ContainerID:` + fmt.Sprintf("%v", this.ContainerID) + `,`,
		`NetworkNamespace:` + fmt.Sprintf("%v", this.NetworkNamespace) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ConfigureContainerNetworkingResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ConfigureContainerNetworkingResponse{`,
		`Success:` + fmt.Sprintf("%v", this.Success) + `,`,
		`ResponseJson:` + fmt.Sprintf("%v", this.ResponseJson) + `,`,
		`ErrorJson:` + fmt.Sprintf("%v", this.ErrorJson) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringNodenetsvc(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ConfigureNetworkingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigureNetworkingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigureNetworkingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContainerID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigureNetworkingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigureNetworkingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigureNetworkingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PingNodeNetworkServiceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingNodeNetworkServiceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingNodeNetworkServiceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PingRequestMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PingRequestMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PingNodeNetworkServiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingNodeNetworkServiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingNodeNetworkServiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigureContainerNetworkingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigureContainerNetworkingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigureContainerNetworkingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestType", wireType)
			}
			m.RequestType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestType |= RequestType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContainerID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkNamespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkNamespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigureContainerNetworkingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigureContainerNetworkingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigureContainerNetworkingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResponseJson", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResponseJson = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorJson", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorJson = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNodenetsvc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNodenetsvc
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthNodenetsvc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowNodenetsvc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipNodenetsvc(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthNodenetsvc
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthNodenetsvc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNodenetsvc   = fmt.Errorf("proto: integer overflow")
)
