// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/Microsoft/hcsshim/internal/ncproxyttrpc/networkconfigproxy.proto

package ncproxyttrpc

import (
	context "context"
	fmt "fmt"
	github_com_containerd_ttrpc "github.com/containerd/ttrpc"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RequestType int32

const (
	RequestType_RequestType_Setup    RequestType = 0
	RequestType_RequestType_Teardown RequestType = 1
	RequestType_RequestType_Modify   RequestType = 2
)

var RequestType_name = map[int32]string{
	0: "RequestType_Setup",
	1: "RequestType_Teardown",
	2: "RequestType_Modify",
}

var RequestType_value = map[string]int32{
	"RequestType_Setup":    0,
	"RequestType_Teardown": 1,
	"RequestType_Modify":   2,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}

func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_11f9efc6dfbf9b45, []int{0}
}

type RegisterComputeAgentRequest struct {
	AgentAddress         string   `protobuf:"bytes,1,opt,name=agent_address,json=agentAddress,proto3" json:"agent_address,omitempty"`
	ContainerID          string   `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterComputeAgentRequest) Reset()      { *m = RegisterComputeAgentRequest{} }
func (*RegisterComputeAgentRequest) ProtoMessage() {}
func (*RegisterComputeAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11f9efc6dfbf9b45, []int{0}
}
func (m *RegisterComputeAgentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterComputeAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterComputeAgentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterComputeAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterComputeAgentRequest.Merge(m, src)
}
func (m *RegisterComputeAgentRequest) XXX_Size() int {
	return m.Size()
}
func (m *RegisterComputeAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterComputeAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterComputeAgentRequest proto.InternalMessageInfo

type RegisterComputeAgentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterComputeAgentResponse) Reset()      { *m = RegisterComputeAgentResponse{} }
func (*RegisterComputeAgentResponse) ProtoMessage() {}
func (*RegisterComputeAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11f9efc6dfbf9b45, []int{1}
}
func (m *RegisterComputeAgentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterComputeAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterComputeAgentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterComputeAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterComputeAgentResponse.Merge(m, src)
}
func (m *RegisterComputeAgentResponse) XXX_Size() int {
	return m.Size()
}
func (m *RegisterComputeAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterComputeAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterComputeAgentResponse proto.InternalMessageInfo

type ConfigureNetworkingInternalRequest struct {
	ContainerID          string      `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	RequestType          RequestType `protobuf:"varint,2,opt,name=request_type,json=requestType,proto3,enum=RequestType" json:"request_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConfigureNetworkingInternalRequest) Reset()      { *m = ConfigureNetworkingInternalRequest{} }
func (*ConfigureNetworkingInternalRequest) ProtoMessage() {}
func (*ConfigureNetworkingInternalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11f9efc6dfbf9b45, []int{2}
}
func (m *ConfigureNetworkingInternalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigureNetworkingInternalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigureNetworkingInternalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigureNetworkingInternalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureNetworkingInternalRequest.Merge(m, src)
}
func (m *ConfigureNetworkingInternalRequest) XXX_Size() int {
	return m.Size()
}
func (m *ConfigureNetworkingInternalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureNetworkingInternalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureNetworkingInternalRequest proto.InternalMessageInfo

type ConfigureNetworkingInternalResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigureNetworkingInternalResponse) Reset()      { *m = ConfigureNetworkingInternalResponse{} }
func (*ConfigureNetworkingInternalResponse) ProtoMessage() {}
func (*ConfigureNetworkingInternalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11f9efc6dfbf9b45, []int{3}
}
func (m *ConfigureNetworkingInternalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigureNetworkingInternalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigureNetworkingInternalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigureNetworkingInternalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureNetworkingInternalResponse.Merge(m, src)
}
func (m *ConfigureNetworkingInternalResponse) XXX_Size() int {
	return m.Size()
}
func (m *ConfigureNetworkingInternalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureNetworkingInternalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureNetworkingInternalResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("RequestType", RequestType_name, RequestType_value)
	proto.RegisterType((*RegisterComputeAgentRequest)(nil), "RegisterComputeAgentRequest")
	proto.RegisterType((*RegisterComputeAgentResponse)(nil), "RegisterComputeAgentResponse")
	proto.RegisterType((*ConfigureNetworkingInternalRequest)(nil), "ConfigureNetworkingInternalRequest")
	proto.RegisterType((*ConfigureNetworkingInternalResponse)(nil), "ConfigureNetworkingInternalResponse")
}

func init() {
	proto.RegisterFile("github.com/Microsoft/hcsshim/internal/ncproxyttrpc/networkconfigproxy.proto", fileDescriptor_11f9efc6dfbf9b45)
}

var fileDescriptor_11f9efc6dfbf9b45 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0xae, 0xd2, 0x40,
	0x14, 0xed, 0xb0, 0x30, 0x71, 0x5a, 0x15, 0x47, 0x34, 0x04, 0xb1, 0x9a, 0xa2, 0x89, 0x71, 0xd1,
	0x26, 0xb8, 0x74, 0x23, 0xe0, 0x86, 0x18, 0x8c, 0xa9, 0x68, 0x0c, 0x9b, 0xa6, 0xb4, 0x97, 0x32,
	0x51, 0x66, 0xc6, 0x99, 0xa9, 0xd8, 0x9d, 0x5b, 0xff, 0x8c, 0x9d, 0x2e, 0x5d, 0x19, 0xe9, 0x97,
	0x98, 0xb6, 0xe0, 0x6b, 0xde, 0x23, 0xf0, 0xf2, 0x76, 0x73, 0x4e, 0x6f, 0xef, 0x39, 0xe7, 0xde,
	0x8b, 0x5f, 0x27, 0x54, 0x2f, 0xd3, 0xb9, 0x1b, 0xf1, 0x95, 0x37, 0xa1, 0x91, 0xe4, 0x8a, 0x2f,
	0xb4, 0xb7, 0x8c, 0x94, 0x5a, 0xd2, 0x95, 0x47, 0x99, 0x06, 0xc9, 0xc2, 0xcf, 0x1e, 0x8b, 0x84,
	0xe4, 0xdf, 0x32, 0xad, 0xa5, 0x88, 0x3c, 0x06, 0x7a, 0xcd, 0xe5, 0xa7, 0x88, 0xb3, 0x05, 0x4d,
	0x4a, 0xde, 0x15, 0x92, 0x6b, 0xde, 0x69, 0x25, 0x3c, 0xe1, 0xe5, 0xd3, 0x2b, 0x5e, 0x15, 0xeb,
	0x7c, 0xc5, 0xf7, 0x7d, 0x48, 0xa8, 0xd2, 0x20, 0x47, 0x7c, 0x25, 0x52, 0x0d, 0x83, 0x04, 0x98,
	0xf6, 0xe1, 0x4b, 0x0a, 0x4a, 0x93, 0x1e, 0xbe, 0x11, 0x16, 0x38, 0x08, 0xe3, 0x58, 0x82, 0x52,
	0x6d, 0xf4, 0x08, 0x3d, 0xbd, 0xee, 0x5b, 0x25, 0x39, 0xa8, 0x38, 0xd2, 0xc7, 0x56, 0xc4, 0x99,
	0x0e, 0x29, 0x03, 0x19, 0xd0, 0xb8, 0xdd, 0x28, 0x6a, 0x86, 0xb7, 0xf2, 0x3f, 0x0f, 0xcd, 0xd1,
	0x9e, 0x1f, 0xbf, 0xf2, 0xcd, 0xff, 0x45, 0xe3, 0xd8, 0xb1, 0x71, 0xf7, 0xb0, 0xae, 0x12, 0x9c,
	0x29, 0x70, 0x7e, 0x20, 0xec, 0x8c, 0xca, 0x0c, 0xa9, 0x84, 0x37, 0x55, 0x26, 0xca, 0x92, 0xf1,
	0x2e, 0xf3, 0xde, 0xdf, 0x79, 0x69, 0x74, 0x5a, 0x9a, 0x78, 0xd8, 0x92, 0xd5, 0xef, 0x81, 0xce,
	0x04, 0x94, 0x76, 0x6f, 0xf6, 0x2d, 0x77, 0xd7, 0x73, 0x9a, 0x09, 0xf0, 0x4d, 0x79, 0x06, 0x9c,
	0x27, 0xb8, 0x77, 0xd4, 0x4a, 0x65, 0xf9, 0xd9, 0x07, 0x6c, 0xd6, 0x5a, 0x90, 0xbb, 0xf8, 0x76,
	0x0d, 0x06, 0xef, 0x40, 0xa7, 0xa2, 0x69, 0x90, 0x36, 0x6e, 0xd5, 0xe9, 0x29, 0x84, 0x32, 0xe6,
	0x6b, 0xd6, 0x44, 0xe4, 0x1e, 0x26, 0xf5, 0x2f, 0x13, 0x1e, 0xd3, 0x45, 0xd6, 0x6c, 0xf4, 0x7f,
	0x22, 0x4c, 0x76, 0xb2, 0x95, 0x8d, 0xb7, 0xc5, 0x56, 0xc9, 0xfb, 0xa2, 0xd1, 0xc5, 0x09, 0x92,
	0xae, 0x7b, 0x64, 0xa1, 0x9d, 0x07, 0xee, 0xd1, 0xb1, 0x1b, 0x64, 0x8e, 0xef, 0x1c, 0x08, 0x4b,
	0x7a, 0xee, 0xe9, 0x6d, 0x74, 0x1e, 0xbb, 0x97, 0x98, 0x93, 0x63, 0x0c, 0x67, 0x9b, 0xad, 0x6d,
	0xfc, 0xde, 0xda, 0xc6, 0xf7, 0xdc, 0x46, 0x9b, 0xdc, 0x46, 0xbf, 0x72, 0x1b, 0xfd, 0xcd, 0x6d,
	0x34, 0x7b, 0x79, 0x85, 0x8b, 0x7f, 0x51, 0x47, 0x1f, 0x8d, 0xf9, 0xb5, 0xf2, 0xb2, 0x9f, 0xff,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0xed, 0x67, 0x27, 0x00, 0x3e, 0x03, 0x00, 0x00,
}

func (m *RegisterComputeAgentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterComputeAgentRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.AgentAddress) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintNetworkconfigproxy(dAtA, i, uint64(len(m.AgentAddress)))
		i += copy(dAtA[i:], m.AgentAddress)
	}
	if len(m.ContainerID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintNetworkconfigproxy(dAtA, i, uint64(len(m.ContainerID)))
		i += copy(dAtA[i:], m.ContainerID)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *RegisterComputeAgentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterComputeAgentResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ConfigureNetworkingInternalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigureNetworkingInternalRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ContainerID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintNetworkconfigproxy(dAtA, i, uint64(len(m.ContainerID)))
		i += copy(dAtA[i:], m.ContainerID)
	}
	if m.RequestType != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintNetworkconfigproxy(dAtA, i, uint64(m.RequestType))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ConfigureNetworkingInternalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigureNetworkingInternalResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintNetworkconfigproxy(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RegisterComputeAgentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AgentAddress)
	if l > 0 {
		n += 1 + l + sovNetworkconfigproxy(uint64(l))
	}
	l = len(m.ContainerID)
	if l > 0 {
		n += 1 + l + sovNetworkconfigproxy(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RegisterComputeAgentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ConfigureNetworkingInternalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContainerID)
	if l > 0 {
		n += 1 + l + sovNetworkconfigproxy(uint64(l))
	}
	if m.RequestType != 0 {
		n += 1 + sovNetworkconfigproxy(uint64(m.RequestType))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ConfigureNetworkingInternalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovNetworkconfigproxy(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozNetworkconfigproxy(x uint64) (n int) {
	return sovNetworkconfigproxy(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *RegisterComputeAgentRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RegisterComputeAgentRequest{`,
		`AgentAddress:` + fmt.Sprintf("%v", this.AgentAddress) + `,`,
		`ContainerID:` + fmt.Sprintf("%v", this.ContainerID) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RegisterComputeAgentResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RegisterComputeAgentResponse{`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ConfigureNetworkingInternalRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ConfigureNetworkingInternalRequest{`,
		`ContainerID:` + fmt.Sprintf("%v", this.ContainerID) + `,`,
		`RequestType:` + fmt.Sprintf("%v", this.RequestType) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ConfigureNetworkingInternalResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ConfigureNetworkingInternalResponse{`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringNetworkconfigproxy(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}

type NetworkConfigProxyService interface {
	RegisterComputeAgent(ctx context.Context, req *RegisterComputeAgentRequest) (*RegisterComputeAgentResponse, error)
	ConfigureNetworking(ctx context.Context, req *ConfigureNetworkingInternalRequest) (*ConfigureNetworkingInternalResponse, error)
}

func RegisterNetworkConfigProxyService(srv *github_com_containerd_ttrpc.Server, svc NetworkConfigProxyService) {
	srv.Register("NetworkConfigProxy", map[string]github_com_containerd_ttrpc.Method{
		"RegisterComputeAgent": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req RegisterComputeAgentRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.RegisterComputeAgent(ctx, &req)
		},
		"ConfigureNetworking": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req ConfigureNetworkingInternalRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.ConfigureNetworking(ctx, &req)
		},
	})
}

type networkConfigProxyClient struct {
	client *github_com_containerd_ttrpc.Client
}

func NewNetworkConfigProxyClient(client *github_com_containerd_ttrpc.Client) NetworkConfigProxyService {
	return &networkConfigProxyClient{
		client: client,
	}
}

func (c *networkConfigProxyClient) RegisterComputeAgent(ctx context.Context, req *RegisterComputeAgentRequest) (*RegisterComputeAgentResponse, error) {
	var resp RegisterComputeAgentResponse
	if err := c.client.Call(ctx, "NetworkConfigProxy", "RegisterComputeAgent", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *networkConfigProxyClient) ConfigureNetworking(ctx context.Context, req *ConfigureNetworkingInternalRequest) (*ConfigureNetworkingInternalResponse, error) {
	var resp ConfigureNetworkingInternalResponse
	if err := c.client.Call(ctx, "NetworkConfigProxy", "ConfigureNetworking", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
func (m *RegisterComputeAgentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNetworkconfigproxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterComputeAgentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterComputeAgentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetworkconfigproxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetworkconfigproxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContainerID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNetworkconfigproxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisterComputeAgentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNetworkconfigproxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterComputeAgentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterComputeAgentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipNetworkconfigproxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigureNetworkingInternalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNetworkconfigproxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigureNetworkingInternalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigureNetworkingInternalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetworkconfigproxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContainerID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestType", wireType)
			}
			m.RequestType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetworkconfigproxy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestType |= RequestType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNetworkconfigproxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigureNetworkingInternalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNetworkconfigproxy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigureNetworkingInternalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigureNetworkingInternalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipNetworkconfigproxy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNetworkconfigproxy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNetworkconfigproxy(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNetworkconfigproxy
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNetworkconfigproxy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNetworkconfigproxy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNetworkconfigproxy
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthNetworkconfigproxy
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowNetworkconfigproxy
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipNetworkconfigproxy(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthNetworkconfigproxy
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthNetworkconfigproxy = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNetworkconfigproxy   = fmt.Errorf("proto: integer overflow")
)
