/*
 * HCS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type Device struct {
	// TODO katiewasnothere: this needs to be updated to the latest version
	//  The interface class guid of the device to assign to container.
	InterfaceClassGuid string `json:"InterfaceClassGuid,omitempty"`
}
