/*
 * HCS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type InterruptModerationMode uint32

// The valid interrupt moderation modes for I/O virtualization (IOV) offloading.
const (
	Default  InterruptModerationMode = 0
	Adaptive InterruptModerationMode = 1
	Off      InterruptModerationMode = 2
	Low      InterruptModerationMode = 100
	Medium   InterruptModerationMode = 200
	High     InterruptModerationMode = 300
)
