// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/Microsoft/hcsshim/internal/computeagent/computeagent.proto

package computeagent

import (
	context "context"
	fmt "fmt"
	github_com_containerd_ttrpc "github.com/containerd/ttrpc"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type AddNICInternalRequest struct {
	ContainerID          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	NicID                string   `protobuf:"bytes,2,opt,name=nic_id,json=nicId,proto3" json:"nic_id,omitempty"`
	EndpointName         string   `protobuf:"bytes,3,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNICInternalRequest) Reset()      { *m = AddNICInternalRequest{} }
func (*AddNICInternalRequest) ProtoMessage() {}
func (*AddNICInternalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f2f03dc308add4c, []int{0}
}
func (m *AddNICInternalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddNICInternalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddNICInternalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddNICInternalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNICInternalRequest.Merge(m, src)
}
func (m *AddNICInternalRequest) XXX_Size() int {
	return m.Size()
}
func (m *AddNICInternalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNICInternalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNICInternalRequest proto.InternalMessageInfo

type AddNICInternalResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNICInternalResponse) Reset()      { *m = AddNICInternalResponse{} }
func (*AddNICInternalResponse) ProtoMessage() {}
func (*AddNICInternalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f2f03dc308add4c, []int{1}
}
func (m *AddNICInternalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddNICInternalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddNICInternalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddNICInternalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNICInternalResponse.Merge(m, src)
}
func (m *AddNICInternalResponse) XXX_Size() int {
	return m.Size()
}
func (m *AddNICInternalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNICInternalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddNICInternalResponse proto.InternalMessageInfo

type DeleteNICInternalRequest struct {
	ContainerID          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	NicID                string   `protobuf:"bytes,2,opt,name=nic_id,json=nicId,proto3" json:"nic_id,omitempty"`
	EndpointName         string   `protobuf:"bytes,3,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNICInternalRequest) Reset()      { *m = DeleteNICInternalRequest{} }
func (*DeleteNICInternalRequest) ProtoMessage() {}
func (*DeleteNICInternalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f2f03dc308add4c, []int{2}
}
func (m *DeleteNICInternalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteNICInternalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteNICInternalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteNICInternalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNICInternalRequest.Merge(m, src)
}
func (m *DeleteNICInternalRequest) XXX_Size() int {
	return m.Size()
}
func (m *DeleteNICInternalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNICInternalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNICInternalRequest proto.InternalMessageInfo

type DeleteNICInternalResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNICInternalResponse) Reset()      { *m = DeleteNICInternalResponse{} }
func (*DeleteNICInternalResponse) ProtoMessage() {}
func (*DeleteNICInternalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f2f03dc308add4c, []int{3}
}
func (m *DeleteNICInternalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteNICInternalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteNICInternalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteNICInternalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNICInternalResponse.Merge(m, src)
}
func (m *DeleteNICInternalResponse) XXX_Size() int {
	return m.Size()
}
func (m *DeleteNICInternalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNICInternalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNICInternalResponse proto.InternalMessageInfo

type ModifyNICInternalRequest struct {
	NicID                string   `protobuf:"bytes,1,opt,name=nic_id,json=nicId,proto3" json:"nic_id,omitempty"`
	EndpointName         string   `protobuf:"bytes,2,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"`
	IovWeight            uint32   `protobuf:"varint,3,opt,name=iov_weight,json=iovWeight,proto3" json:"iov_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyNICInternalRequest) Reset()      { *m = ModifyNICInternalRequest{} }
func (*ModifyNICInternalRequest) ProtoMessage() {}
func (*ModifyNICInternalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f2f03dc308add4c, []int{4}
}
func (m *ModifyNICInternalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ModifyNICInternalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ModifyNICInternalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ModifyNICInternalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyNICInternalRequest.Merge(m, src)
}
func (m *ModifyNICInternalRequest) XXX_Size() int {
	return m.Size()
}
func (m *ModifyNICInternalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyNICInternalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyNICInternalRequest proto.InternalMessageInfo

type ModifyNICInternalResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyNICInternalResponse) Reset()      { *m = ModifyNICInternalResponse{} }
func (*ModifyNICInternalResponse) ProtoMessage() {}
func (*ModifyNICInternalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f2f03dc308add4c, []int{5}
}
func (m *ModifyNICInternalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ModifyNICInternalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ModifyNICInternalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ModifyNICInternalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyNICInternalResponse.Merge(m, src)
}
func (m *ModifyNICInternalResponse) XXX_Size() int {
	return m.Size()
}
func (m *ModifyNICInternalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyNICInternalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyNICInternalResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AddNICInternalRequest)(nil), "AddNICInternalRequest")
	proto.RegisterType((*AddNICInternalResponse)(nil), "AddNICInternalResponse")
	proto.RegisterType((*DeleteNICInternalRequest)(nil), "DeleteNICInternalRequest")
	proto.RegisterType((*DeleteNICInternalResponse)(nil), "DeleteNICInternalResponse")
	proto.RegisterType((*ModifyNICInternalRequest)(nil), "ModifyNICInternalRequest")
	proto.RegisterType((*ModifyNICInternalResponse)(nil), "ModifyNICInternalResponse")
}

func init() {
	proto.RegisterFile("github.com/Microsoft/hcsshim/internal/computeagent/computeagent.proto", fileDescriptor_7f2f03dc308add4c)
}

var fileDescriptor_7f2f03dc308add4c = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0xbf, 0xae, 0xda, 0x30,
	0x14, 0xc6, 0x63, 0x2a, 0x90, 0x62, 0x40, 0x95, 0xac, 0x96, 0x86, 0x54, 0x0d, 0x28, 0x5d, 0x3a,
	0x39, 0x12, 0x1d, 0x19, 0x2a, 0x20, 0x1d, 0x32, 0xc0, 0x90, 0xa5, 0x7f, 0x16, 0x14, 0x1c, 0x93,
	0x58, 0x22, 0x76, 0x9a, 0x18, 0xaa, 0x6e, 0x3c, 0x43, 0xa5, 0xbe, 0x13, 0x63, 0xb7, 0x76, 0x42,
	0x25, 0x4f, 0x52, 0x25, 0x01, 0xda, 0x7b, 0x6f, 0x22, 0xdd, 0xbb, 0xdd, 0xcd, 0xe7, 0xd3, 0xa7,
	0xa3, 0x9f, 0xbf, 0x73, 0x0e, 0x7c, 0x1f, 0x30, 0x19, 0x6e, 0x57, 0x98, 0x88, 0xc8, 0x9a, 0x33,
	0x92, 0x88, 0x54, 0xac, 0xa5, 0x15, 0x92, 0x34, 0x0d, 0x59, 0x64, 0x31, 0x2e, 0x69, 0xc2, 0xbd,
	0x8d, 0x45, 0x44, 0x14, 0x6f, 0x25, 0xf5, 0x02, 0xca, 0xe5, 0x8d, 0x02, 0xc7, 0x89, 0x90, 0x42,
	0x7f, 0x16, 0x88, 0x40, 0x14, 0x4f, 0x2b, 0x7f, 0x95, 0xaa, 0xf9, 0x1d, 0xc0, 0xe7, 0x13, 0xdf,
	0x5f, 0x38, 0x33, 0xe7, 0xdc, 0xc8, 0xa5, 0x5f, 0xb6, 0x34, 0x95, 0x68, 0x04, 0x3b, 0x44, 0x70,
	0xe9, 0x31, 0x4e, 0x93, 0x25, 0xf3, 0x35, 0x30, 0x04, 0x6f, 0xd4, 0xe9, 0xd3, 0xec, 0x38, 0x68,
	0xcf, 0x2e, 0xba, 0x63, 0xbb, 0xed, 0xab, 0xc9, 0xf1, 0xd1, 0x10, 0xb6, 0x38, 0x23, 0xb9, 0xbb,
	0x51, 0xb8, 0xd5, 0xec, 0x38, 0x68, 0x2e, 0x18, 0x71, 0x6c, 0xb7, 0xc9, 0x19, 0x71, 0x7c, 0xf4,
	0x1a, 0x76, 0x29, 0xf7, 0x63, 0xc1, 0xb8, 0x5c, 0x72, 0x2f, 0xa2, 0xda, 0x93, 0xdc, 0xe8, 0x76,
	0x2e, 0xe2, 0xc2, 0x8b, 0xa8, 0xa9, 0xc1, 0xde, 0x6d, 0xa6, 0x34, 0x16, 0x3c, 0xa5, 0xe6, 0x0f,
	0x00, 0x35, 0x9b, 0x6e, 0xa8, 0xa4, 0x8f, 0x8b, 0xf8, 0x25, 0xec, 0x57, 0x60, 0x9d, 0xa1, 0xf7,
	0x00, 0x6a, 0x73, 0xe1, 0xb3, 0xf5, 0xb7, 0x0a, 0xe8, 0x7f, 0x00, 0xe0, 0xbe, 0x00, 0x8d, 0xbb,
	0x00, 0xe8, 0x15, 0x84, 0x4c, 0xec, 0x96, 0x5f, 0x29, 0x0b, 0x42, 0x59, 0x20, 0x76, 0x5d, 0x95,
	0x89, 0xdd, 0x87, 0x42, 0xc8, 0xf9, 0x2a, 0x08, 0x4a, 0xbe, 0xd1, 0x2f, 0x00, 0x3b, 0xb3, 0x72,
	0x61, 0x26, 0xf9, 0xc2, 0xa0, 0x31, 0x6c, 0x95, 0xf9, 0xa3, 0x1e, 0xae, 0x5c, 0x0e, 0xfd, 0x05,
	0xae, 0x19, 0x90, 0x82, 0x6c, 0xa8, 0x5e, 0xa3, 0x40, 0x7d, 0x5c, 0x37, 0x2d, 0x5d, 0xc7, 0xf5,
	0x89, 0x15, 0x5d, 0xae, 0xc0, 0xa8, 0x8f, 0xeb, 0xe2, 0xd3, 0x75, 0x5c, 0xfb, 0x2f, 0x53, 0x99,
	0x7e, 0x3a, 0x9c, 0x0c, 0xe5, 0xf7, 0xc9, 0x50, 0xf6, 0x99, 0x01, 0x0e, 0x99, 0x01, 0x7e, 0x66,
	0x06, 0xf8, 0x93, 0x19, 0xe0, 0xf3, 0xbb, 0x87, 0x1f, 0xd5, 0xf8, 0xff, 0xe2, 0xa3, 0xb2, 0x6a,
	0x15, 0x17, 0xf4, 0xf6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xf7, 0x0e, 0x08, 0xa0, 0x03,
	0x00, 0x00,
}

func (m *AddNICInternalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddNICInternalRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ContainerID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintComputeagent(dAtA, i, uint64(len(m.ContainerID)))
		i += copy(dAtA[i:], m.ContainerID)
	}
	if len(m.NicID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintComputeagent(dAtA, i, uint64(len(m.NicID)))
		i += copy(dAtA[i:], m.NicID)
	}
	if len(m.EndpointName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintComputeagent(dAtA, i, uint64(len(m.EndpointName)))
		i += copy(dAtA[i:], m.EndpointName)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *AddNICInternalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddNICInternalResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *DeleteNICInternalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteNICInternalRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ContainerID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintComputeagent(dAtA, i, uint64(len(m.ContainerID)))
		i += copy(dAtA[i:], m.ContainerID)
	}
	if len(m.NicID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintComputeagent(dAtA, i, uint64(len(m.NicID)))
		i += copy(dAtA[i:], m.NicID)
	}
	if len(m.EndpointName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintComputeagent(dAtA, i, uint64(len(m.EndpointName)))
		i += copy(dAtA[i:], m.EndpointName)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *DeleteNICInternalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteNICInternalResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ModifyNICInternalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ModifyNICInternalRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.NicID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintComputeagent(dAtA, i, uint64(len(m.NicID)))
		i += copy(dAtA[i:], m.NicID)
	}
	if len(m.EndpointName) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintComputeagent(dAtA, i, uint64(len(m.EndpointName)))
		i += copy(dAtA[i:], m.EndpointName)
	}
	if m.IovWeight != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintComputeagent(dAtA, i, uint64(m.IovWeight))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ModifyNICInternalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ModifyNICInternalResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintComputeagent(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *AddNICInternalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContainerID)
	if l > 0 {
		n += 1 + l + sovComputeagent(uint64(l))
	}
	l = len(m.NicID)
	if l > 0 {
		n += 1 + l + sovComputeagent(uint64(l))
	}
	l = len(m.EndpointName)
	if l > 0 {
		n += 1 + l + sovComputeagent(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AddNICInternalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DeleteNICInternalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContainerID)
	if l > 0 {
		n += 1 + l + sovComputeagent(uint64(l))
	}
	l = len(m.NicID)
	if l > 0 {
		n += 1 + l + sovComputeagent(uint64(l))
	}
	l = len(m.EndpointName)
	if l > 0 {
		n += 1 + l + sovComputeagent(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DeleteNICInternalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ModifyNICInternalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NicID)
	if l > 0 {
		n += 1 + l + sovComputeagent(uint64(l))
	}
	l = len(m.EndpointName)
	if l > 0 {
		n += 1 + l + sovComputeagent(uint64(l))
	}
	if m.IovWeight != 0 {
		n += 1 + sovComputeagent(uint64(m.IovWeight))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ModifyNICInternalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovComputeagent(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozComputeagent(x uint64) (n int) {
	return sovComputeagent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *AddNICInternalRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AddNICInternalRequest{`,
		`ContainerID:` + fmt.Sprintf("%v", this.ContainerID) + `,`,
		`NicID:` + fmt.Sprintf("%v", this.NicID) + `,`,
		`EndpointName:` + fmt.Sprintf("%v", this.EndpointName) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AddNICInternalResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AddNICInternalResponse{`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeleteNICInternalRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteNICInternalRequest{`,
		`ContainerID:` + fmt.Sprintf("%v", this.ContainerID) + `,`,
		`NicID:` + fmt.Sprintf("%v", this.NicID) + `,`,
		`EndpointName:` + fmt.Sprintf("%v", this.EndpointName) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeleteNICInternalResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteNICInternalResponse{`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ModifyNICInternalRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ModifyNICInternalRequest{`,
		`NicID:` + fmt.Sprintf("%v", this.NicID) + `,`,
		`EndpointName:` + fmt.Sprintf("%v", this.EndpointName) + `,`,
		`IovWeight:` + fmt.Sprintf("%v", this.IovWeight) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ModifyNICInternalResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ModifyNICInternalResponse{`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringComputeagent(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}

type ComputeAgentService interface {
	AddNIC(ctx context.Context, req *AddNICInternalRequest) (*AddNICInternalResponse, error)
	DeleteNIC(ctx context.Context, req *DeleteNICInternalRequest) (*DeleteNICInternalResponse, error)
	ModifyNIC(ctx context.Context, req *ModifyNICInternalRequest) (*ModifyNICInternalResponse, error)
}

func RegisterComputeAgentService(srv *github_com_containerd_ttrpc.Server, svc ComputeAgentService) {
	srv.Register("ComputeAgent", map[string]github_com_containerd_ttrpc.Method{
		"AddNIC": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req AddNICInternalRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.AddNIC(ctx, &req)
		},
		"DeleteNIC": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req DeleteNICInternalRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.DeleteNIC(ctx, &req)
		},
		"ModifyNIC": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req ModifyNICInternalRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.ModifyNIC(ctx, &req)
		},
	})
}

type computeAgentClient struct {
	client *github_com_containerd_ttrpc.Client
}

func NewComputeAgentClient(client *github_com_containerd_ttrpc.Client) ComputeAgentService {
	return &computeAgentClient{
		client: client,
	}
}

func (c *computeAgentClient) AddNIC(ctx context.Context, req *AddNICInternalRequest) (*AddNICInternalResponse, error) {
	var resp AddNICInternalResponse
	if err := c.client.Call(ctx, "ComputeAgent", "AddNIC", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *computeAgentClient) DeleteNIC(ctx context.Context, req *DeleteNICInternalRequest) (*DeleteNICInternalResponse, error) {
	var resp DeleteNICInternalResponse
	if err := c.client.Call(ctx, "ComputeAgent", "DeleteNIC", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *computeAgentClient) ModifyNIC(ctx context.Context, req *ModifyNICInternalRequest) (*ModifyNICInternalResponse, error) {
	var resp ModifyNICInternalResponse
	if err := c.client.Call(ctx, "ComputeAgent", "ModifyNIC", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
func (m *AddNICInternalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowComputeagent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddNICInternalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddNICInternalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComputeagent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComputeagent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContainerID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NicID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComputeagent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComputeagent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NicID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndpointName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComputeagent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComputeagent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndpointName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipComputeagent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddNICInternalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowComputeagent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddNICInternalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddNICInternalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipComputeagent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteNICInternalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowComputeagent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteNICInternalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteNICInternalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComputeagent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComputeagent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContainerID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NicID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComputeagent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComputeagent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NicID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndpointName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComputeagent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComputeagent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndpointName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipComputeagent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteNICInternalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowComputeagent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteNICInternalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteNICInternalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipComputeagent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ModifyNICInternalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowComputeagent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ModifyNICInternalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ModifyNICInternalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NicID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComputeagent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComputeagent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NicID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndpointName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComputeagent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComputeagent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndpointName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IovWeight", wireType)
			}
			m.IovWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IovWeight |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipComputeagent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ModifyNICInternalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowComputeagent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ModifyNICInternalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ModifyNICInternalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipComputeagent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipComputeagent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowComputeagent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthComputeagent
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthComputeagent
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowComputeagent
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipComputeagent(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthComputeagent
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthComputeagent = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowComputeagent   = fmt.Errorf("proto: integer overflow")
)
